#!/usr/bin/env sh
# llvm-slice installer -- no Python required.
#
# Installs the self-contained `jac` runtime (a single binary published by the
# Jaseci project) plus the tiny llvm-slice sources, and drops a `llvm-slice`
# launcher on your PATH.
#
#   curl -fsSL https://raw.githubusercontent.com/jaseci-labs/llvm-slice/main/install.sh | sh
#
# Tunable via environment variables:
#   JAC_VERSION          jac runtime version to fetch        (default below)
#   LLVM_SLICE_REF       git ref of the sources to install   (default: main)
#   LLVM_SLICE_PREFIX    install root                        (default: ~/.llvm-slice)
#   LLVM_SLICE_BINDIR    where the launcher is written        (default: ~/.local/bin)
#
# Supported platforms: linux-x86_64, linux-aarch64, macos-aarch64 (the targets
# the jac runtime ships for). On any other platform, install from PyPI instead:
#   pipx install llvm-slice
set -eu

JAC_VERSION="${JAC_VERSION:-0.30.1}"
JAC_REPO="jaseci-labs/jaseci"
TOOL_REPO="${LLVM_SLICE_REPO:-jaseci-labs/llvm-slice}"
REF="${LLVM_SLICE_REF:-main}"
PREFIX="${LLVM_SLICE_PREFIX:-$HOME/.llvm-slice}"
BINDIR="${LLVM_SLICE_BINDIR:-$HOME/.local/bin}"

say()  { printf '%s\n' "$*"; }
err()  { printf 'error: %s\n' "$*" >&2; }
die()  { err "$*"; exit 1; }

# --- pick a downloader -------------------------------------------------------
if command -v curl >/dev/null 2>&1; then
  dl() { curl -fsSL "$1" -o "$2"; }
elif command -v wget >/dev/null 2>&1; then
  dl() { wget -qO "$2" "$1"; }
else
  die "need curl or wget on PATH"
fi

# --- detect platform ---------------------------------------------------------
os="$(uname -s)"; arch="$(uname -m)"
case "$os" in
  Linux)  jos="linux" ;;
  Darwin) jos="macos" ;;
  *) die "unsupported OS '$os' -- install from PyPI instead: pipx install llvm-slice" ;;
esac
case "$arch" in
  x86_64|amd64)  jarch="x86_64" ;;
  arm64|aarch64) jarch="aarch64" ;;
  *) die "unsupported arch '$arch' -- install from PyPI instead: pipx install llvm-slice" ;;
esac
case "${jos}-${jarch}" in
  linux-x86_64|linux-aarch64|macos-aarch64) ;;
  *) die "no prebuilt jac runtime for ${jos}-${jarch} -- install from PyPI instead: pipx install llvm-slice" ;;
esac
asset="jac-${JAC_VERSION}-${jos}-${jarch}"

# --- portable sha256 ---------------------------------------------------------
sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | awk '{print $1}'
  elif command -v shasum  >/dev/null 2>&1; then shasum -a 256 "$1" | awk '{print $1}'
  else printf ''; fi
}

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT INT TERM

# --- 1. fetch + verify the jac runtime --------------------------------------
jbase="https://github.com/${JAC_REPO}/releases/download/jaclang-${JAC_VERSION}"
say "Downloading jac runtime ${asset} ..."
dl "${jbase}/${asset}"        "$tmp/jac"        || die "failed to download ${asset}"
dl "${jbase}/${asset}.sha256" "$tmp/jac.sha256" || die "failed to download checksum"
want="$(awk '{print $1}' "$tmp/jac.sha256")"
got="$(sha256_of "$tmp/jac")"
if [ -n "$got" ] && [ "$want" != "$got" ]; then
  die "checksum mismatch for ${asset} (expected $want, got $got)"
fi
[ -n "$got" ] || say "  (no sha256 tool found; skipping checksum verification)"
chmod +x "$tmp/jac"

# --- 2. fetch the llvm-slice sources ----------------------------------------
say "Downloading llvm-slice sources (${REF}) ..."
dl "https://github.com/${TOOL_REPO}/archive/${REF}.tar.gz" "$tmp/src.tar.gz" \
  || die "failed to download sources for ref '${REF}'"
mkdir -p "$tmp/src"
tar -xzf "$tmp/src.tar.gz" -C "$tmp/src" --strip-components=1 \
  || die "failed to extract sources"
[ -d "$tmp/src/llvm_slice" ] || die "sources missing llvm_slice/ (bad ref '${REF}'?)"

# --- 3. install --------------------------------------------------------------
say "Installing to ${PREFIX} ..."
mkdir -p "$PREFIX" "$BINDIR"
rm -rf "$PREFIX/src"
mkdir -p "$PREFIX/src"
cp -R "$tmp/src/llvm_slice" "$PREFIX/src/llvm_slice"
install -m 0755 "$tmp/jac" "$PREFIX/jac" 2>/dev/null || { cp "$tmp/jac" "$PREFIX/jac"; chmod 0755 "$PREFIX/jac"; }
printf '%s\n' "$JAC_VERSION" > "$PREFIX/JAC_VERSION"

cat > "$BINDIR/llvm-slice" <<EOF
#!/usr/bin/env sh
# llvm-slice launcher (generated by install.sh). Runs from the source root so
# the llvm_slice.* imports resolve, using the bundled jac runtime.
set -eu
cd "$PREFIX/src"
exec "$PREFIX/jac" run llvm_slice/cli.jac -- "\$@"
EOF
chmod 0755 "$BINDIR/llvm-slice"

# --- 4. report ---------------------------------------------------------------
say ""
say "Installed: $BINDIR/llvm-slice  (jac runtime $JAC_VERSION)"
case ":$PATH:" in
  *":$BINDIR:"*) ;;
  *) say "NOTE: $BINDIR is not on your PATH. Add this to your shell profile:"
     say "        export PATH=\"$BINDIR:\$PATH\"" ;;
esac
say ""
say "Try:  llvm-slice list --version 22.1.8 --triple x86_64-linux"
say "(first run unpacks the jac runtime and may take a few seconds)"
